### ISSUE TITLE
Tracking reports

### ISSUE THREAD

**Issue by 1beb** [Crunch-io/crunchtabs#107]
- [x] Allow for tracking reports crosstab by wave

**Comment by 1beb** [comment]
- [ ] Add ability to relabel specific questions
- [ ] Add ability to add questions "where they exist" so, questions that are in n-1 waves are still presented

Categorical Arrays: 

- [ ] Make it clear that categorical arrays are all from the same question. Do not repeat headers, have subheaders instead
- [x] Verify functionality of stub-width management. (See tableHeader.ToplineCategoricalArray)

Alternative Usage: 

- [x] Think about secondary use case as "partial cross tab" (example, same categoricals across dataasets, wave_labels are the names of different datasets) 

Example alternative use: 

![image](https://user-images.githubusercontent.com/421859/99837324-6a343700-2b35-11eb-82d1-9ddcf02920bf.png)


```
library(crunchtabs)
login()

places <- sort(c("St Louis", "Memphis", "Detroit", "Charlotte", "Baltimore", "Birmingham"))
ds_names <- sprintf("Campaign Zero %s October 2020 testing fork", places)
ds_names[3] <- "Campaign Zero Charlotte November 2020"
ds_list <- lapply(ds_names, loadDataset)
# civil_assets_
vars <- "noknock_supop, asset_forfeiture_reask, compliance_window, officers_visible"
vars <- unlist(strsplit(vars, ", "))

ct <- tracking_report(ds_list, wave_label = places, 
                      vars = vars)

writeLatex(ct, pdf = TRUE)
```
