### ISSUE TITLE
Tracking Reports Adjustments

### ISSUE THREAD

**Issue by 1beb** [Crunch-io/crunchtabs#232]
- [x] Add ability to relabel specific questions
- [x] Add ability to include questions where they exist so if a question is included in the variable list, it should be included.
- [x] Make it clearer that categorical arrays are all from the same question

**Comment by 1beb** [comment]
Closed by #251
