### ISSUE TITLE
Organizing Issue

### ISSUE THREAD

**Issue by 1beb** [Crunch-io/crunchtabs#64]
Refer to this issue to see progress on other issues. 

In progress:

- [ ] Placeholder

Proposed features: 

- [ ] Add option to enforce one table per page #56
- [ ] Gryphon formatting import #55
- [ ] Relegate issues and warnings #47
